openapi: 3.1.0
info:
  version: 1.0.0
  title: Transactions app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of transactions app
tags:
  - name: Transactions
    description: Operations about transactions.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register/post.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login/post.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh/post.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout/post.yaml'
  /auth/user:
    get:
      $ref: '../swagger/paths/auth/user/get.yaml'
  /auth/user/{id}:
    patch:
      $ref: '../swagger/paths/auth/user/patch.yaml'

  /transactions/{id}:
    put:
      $ref: '../swagger/paths/transactions/{id}/put.yaml'
    delete:
      $ref: '../swagger/paths/transactions/{id}/delete.yaml'

  /transactions:
    post:
      $ref: '../swagger/paths/transactions/post.yaml'

  /summary:
    get:
      $ref: '../swagger/paths/transactions/summary.yaml'

  /transactions/categories:
    get:
      $ref: '../swagger/paths/transactions/categories/getCategories.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
